describe('BSTD 007 - Filter Products', () => {
  it('Select different vendors and verify products', () => {
    cy.visit('https://bstackdemo.com/')
    .get("span")
    .contains("Apple")
    .click()
    .get(".shelf-item")
    .should('have.length',9)
    .get('.shelf-item').each(($el, index, $list) => {
      cy.wrap($el).should('include.text','iPhone')
    })
    .get("span")
    .contains("Apple")
    .click()
    .get("span")
    .contains("Samsung")
    .click()
    .get(".shelf-item")
    .should('have.length',7)
    .get('.shelf-item').each(($el, index, $list) => {
      cy.wrap($el).should('include.text','Galaxy')
    })
    .get("span")
    .contains("Samsung")
    .click()
    .get("span")
    .contains("Google")
    .click()
    .get(".shelf-item")
    .should('have.length',3)
    .get('.shelf-item').each(($el, index, $list) => {
      cy.wrap($el).should('include.text','Pixel')
    })
    .get("span")
    .contains("Google")
    .click()
    .get("span")
    .contains("OnePlus")
    .click()
    .get(".shelf-item")
    .should('have.length',6)
    .get('.shelf-item').each(($el, index, $list) => {
      cy.wrap($el).should('include.text','One Plus')
    })
  })
})
