describe('BSTD-012 Cart With Login', () => {
  it('Visit bstackdemo,sign in, add to cart, click checkout', () => {
    cy.visit('https://bstackdemo.com/')
    .get("#signin")
    .click()
    .get("#react-select-2-input")
    .type("demouser{enter}",{force: true})
    .get("#react-select-3-input")
    .type("testingisfun99{enter}",{force: true})
    .get("#login-btn")
    .click()
    .get(".float-cart__content")
    .should('not.be.visible')
    .get(".shelf-item:nth-child(3) > .shelf-item__buy-btn")
    .click()
    .should('be.visible')
    .get(".buy-btn")
    .click()
    .get(".checkoutHeader-link")
    .should("be.visible")
  })
})
